### ISSUE TITLE
Elide build metadata for dependencies in `workspace-hack`

### ISSUE THREAD

**Issue by benesch** [guppy-rs/guppy#52]
Hey @sunshowers!

We've been using hakari happily for a couple weeks now in the [MaterializeInc/materialize](https://github.com/MaterializeInc/materialize) repository with one little nit—builds now produce this (harmless) warning:

```
warning: /Users/benesch/Sites/materialize/materialize/src/workspace-hack/Cargo.toml: version requirement `0.4.2+5.2.1-patched.2` for dependency `tikv-jemalloc-sys` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
```

The reason is that the workspace-hack crate includes the build metadata when it writes the `tikv-jemalloc-sys` dependency into that crate's Cargo.toml:

https://github.com/MaterializeInc/materialize/blob/92bd33f24a132018716783be2566f48515b52d67/src/workspace-hack/Cargo.toml#L228

Manually removing the build metadata from the Cargo.toml doesn't help, since it comes right back on the next `cargo hakari generate`.

Seems to me like `cargo hakari` should unconditionally strip metadata when writing a Cargo.toml? But not sure if there is some wrinkle I'm not seeing.

**Comment by sunshowers** [comment]
Ahh yeah, thanks for reporting this! Would you like to submit a patch for this?

Looks like this is an issue when exact-versions is specified, so it's really a matter of patching this to not print out exact versions: https://github.com/guppy-rs/guppy/blob/main/tools/hakari/src/helpers.rs#L25-L27

We'd need to do three things here:

1. Elide build metadata from the display. (Would you like to submit a patch for this?)
2. Add this as a new "format version" 3 so that existing users of hakari aren't affected. (I can probably handle this if it's too confusing).
3. Update the default in https://github.com/guppy-rs/guppy/blob/main/tools/hakari/templates/hakari.toml-in#L5-L6 from 2 to 3.

**Comment by benesch** [comment]
I did step 1 in #57! Need your help for steps 2 and 3, though; see questions in PR.

**Comment by sunshowers** [comment]
This is now out as part of cargo-hakari 0.9.18. Thanks again!
